language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - dbt deps
  - dbt compile
# command to run tests
script:
  - dbt run --models tag:raw
  - dbt run --models +tag:stage
  - dbt test
branches:
  only:
    - master
